services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      PORT: 3000
      JWT_SECRET: change-me
      DATABASE_URL: postgresql://postgres:postgres@db:5432/survey_api?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
